version: 2
registries:
  test-internal:
    type: npm-registry
    url: http://169.254.169.254/
    token: dummy-canary-token
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - test-internal
